allExec = ride gift friday beads

all:	$(allExec)

ride:	ride.o
	gcc -o ride ride.o

gift:	gift.o
	g++ -o gift gift.o

friday:	friday.o
	gcc -o friday friday.o

beads:	beads.o
	gcc -o beads beads.o

clean:
	rm $(allExec)
	rm *.o
